# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Tomohiro Koana
title: Theoretical Computer Scientist
email: tomohiro.koana@gmail.com
url: "https://tomohirokoana.github.io"
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Project Assistant Professor (特任助教) at the University of Tokyo.
  My research is in theoretical computer science, especially the design and analysis of algorithms for NP-hard problems.
  I am currently interested in algebraic methods for faster exponential-time algorithms, parameterized and exact algorithms, graph and matroid algorithms, counting problems, derandomization, and time-space tradeoffs.

# Projects Section
projects_title: Selected Publications

# Experience Section
# experience_title: Experience

# Education Section
education_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
# footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
